// Adapted from Fumadocs UI (https://github.com/fuma-nama/fumadocs)
// Copyright (c) 2023 Fuma, MIT License
"use client";

import { cn } from "cn";
import { Check, Clipboard } from "lucide-react";
import {
  type ComponentProps,
  createContext,
  type CSSProperties,
  type HTMLAttributes,
  type ReactNode,
  type RefObject,
  use,
  useMemo,
  useRef,
  useState,
} from "react";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { mergeRefs } from "../utils/merge-refs";
import { useTabsGroup } from "../utils/tabs-group";
import { useCopyButton } from "../utils/use-copy-button";

export interface CodeBlockProps extends Omit<
  ComponentProps<"figure">,
  "title"
> {
  title?: ReactNode;

  /**
   * Icon of code block
   *
   * When passed as a string, it assumes the value is the HTML of icon
   */
  icon?: ReactNode;

  /**
   * Allow to copy code with copy button
   *
   * @defaultValue true
   */
  allowCopy?: boolean | "true" | "false";

  /**
   * Keep original background color generated by Shiki or Rehype Code
   *
   * @defaultValue false
   */
  keepBackground?: boolean;

  viewportProps?: HTMLAttributes<HTMLElement>;

  /**
   * show line numbers
   */
  "data-line-numbers"?: boolean;

  /**
   * @defaultValue 1
   */
  "data-line-numbers-start"?: number;

  Actions?: (props: { className?: string; children?: ReactNode }) => ReactNode;
}

const TabsContext = createContext<{
  containerRef: RefObject<HTMLDivElement | null>;
  nested: boolean;
} | null>(null);

export function Pre(props: ComponentProps<"pre">) {
  return (
    <pre
      {...props}
      className={cn("w-max min-w-full *:flex *:flex-col", props.className)}
    >
      {props.children}
    </pre>
  );
}

export function CodeBlock({
  ref,
  title,
  allowCopy = true,
  keepBackground = false,
  icon,
  viewportProps = {},
  children,
  Actions = (props) => (
    <div {...props} className={cn("empty:hidden", props.className)} />
  ),
  ...props
}: CodeBlockProps) {
  const inTab = use(TabsContext) !== null;
  const areaRef = useRef<HTMLDivElement>(null);
  if (allowCopy === "true") allowCopy = true;
  else if (allowCopy === "false") allowCopy = false;

  return (
    <figure
      ref={ref}
      dir="ltr"
      {...props}
      tabIndex={-1}
      className={cn(
        inTab
          ? "-mx-px -mb-px bg-muted/50 last:rounded-b-xl"
          : "my-4 rounded-xl bg-card",
        keepBackground && "bg-(--shiki-light-bg) dark:bg-(--shiki-dark-bg)",
        "shiki not-docs-typeset relative overflow-hidden border text-sm shadow-xs",
        props.className,
      )}
    >
      {title ? (
        <div className="flex h-9.5 items-center gap-2 border-b px-4 text-muted-foreground">
          {typeof icon === "string" ? (
            <div
              className="[&_svg]:size-3.5"
              dangerouslySetInnerHTML={{
                __html: icon,
              }}
            />
          ) : (
            icon
          )}
          <figcaption className="flex-1 truncate">{title}</figcaption>
          {Actions({
            className: "-me-2",
            children: allowCopy && <CopyButton containerRef={areaRef} />,
          })}
        </div>
      ) : (
        Actions({
          className:
            "absolute top-2 right-2 z-2 rounded-lg text-muted-foreground backdrop-blur-lg",
          children: allowCopy && <CopyButton containerRef={areaRef} />,
        })
      )}
      <div
        ref={areaRef}
        {...viewportProps}
        role="region"
        tabIndex={0}
        className={cn(
          "max-h-[600px] [scrollbar-width:thin] overflow-auto py-3.5 text-[0.8125rem] focus-visible:ring-2 focus-visible:ring-ring focus-visible:outline-none focus-visible:ring-inset",
          viewportProps.className,
        )}
        style={
          {
            // space for toolbar
            "--padding-right": !title ? "calc(var(--spacing) * 8)" : undefined,
            counterSet: props["data-line-numbers"]
              ? `line ${Number(props["data-line-numbers-start"] ?? 1) - 1}`
              : undefined,
            ...viewportProps.style,
          } as CSSProperties
        }
      >
        {children}
      </div>
    </figure>
  );
}

function CopyButton({
  className,
  containerRef,
  ...props
}: ComponentProps<typeof Button> & {
  containerRef: RefObject<HTMLElement | null>;
}) {
  const [checked, onClick] = useCopyButton(() => {
    const pre = containerRef.current?.getElementsByTagName("pre").item(0);
    if (!pre) return;

    const clone = pre.cloneNode(true) as HTMLElement;
    clone.querySelectorAll(".nd-copy-ignore").forEach((node) => {
      node.replaceWith("\n");
    });

    return navigator.clipboard.writeText(clone.textContent ?? "");
  });

  return (
    <Button
      type="button"
      variant="ghost"
      size="icon-xs"
      data-checked={checked || undefined}
      className={cn("data-checked:text-foreground", className)}
      aria-live="polite"
      onClick={onClick}
      {...props}
    >
      {checked ? <Check /> : <Clipboard />}
      <span className="sr-only">{checked ? "Copied Text" : "Copy Text"}</span>
    </Button>
  );
}

type WithStringClassName<T> = Omit<T, "className"> & { className?: string };

export interface CodeBlockTabsProps extends WithStringClassName<
  ComponentProps<typeof Tabs>
> {
  /**
   * Identifier for sharing the selected tab between tab groups
   */
  groupId?: string;

  /**
   * Persist the selected tab in `localStorage` (requires `groupId`)
   */
  persist?: boolean;
}

export function CodeBlockTabs({
  ref,
  className,
  groupId,
  persist = false,
  defaultValue,
  value: _value,
  onValueChange: _onValueChange,
  ...props
}: CodeBlockTabsProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const nested = use(TabsContext) !== null;
  const [uncontrolledValue, setUncontrolledValue] = useState(defaultValue);
  // the value selected in another tab group with the same `groupId`
  const [groupValue, setGroupValue] = useTabsGroup(groupId, persist);
  const value = _value ?? groupValue ?? uncontrolledValue;

  return (
    <Tabs
      ref={mergeRefs(containerRef, ref)}
      value={value}
      onValueChange={(v, details) => {
        if (typeof v === "string") setGroupValue(v);
        setUncontrolledValue(v);
        _onValueChange?.(v, details);
      }}
      {...props}
      className={cn(
        "not-docs-typeset gap-0 rounded-xl border bg-card",
        !nested && "my-4",
        className,
      )}
    >
      <TabsContext
        value={useMemo(
          () => ({
            containerRef,
            nested,
          }),
          [nested],
        )}
      >
        {props.children}
      </TabsContext>
    </Tabs>
  );
}

export function CodeBlockTabsList({
  className,
  ...props
}: WithStringClassName<ComponentProps<typeof TabsList>>) {
  return (
    <TabsList
      variant="line"
      {...props}
      className={cn(
        "w-full justify-start gap-0 overflow-x-auto px-2 group-data-horizontal/tabs:h-auto",
        className,
      )}
    >
      {props.children}
    </TabsList>
  );
}

export function CodeBlockTabsTrigger({
  className,
  ...props
}: WithStringClassName<ComponentProps<typeof TabsTrigger>>) {
  return (
    <TabsTrigger
      {...props}
      className={cn(
        "flex-none gap-2 px-2 py-1.5 text-sm text-muted-foreground group-data-horizontal/tabs:after:inset-x-2 group-data-horizontal/tabs:after:bottom-0 group-data-horizontal/tabs:after:h-px hover:text-foreground data-active:text-foreground [&_svg]:size-3.5",
        className,
      )}
    />
  );
}

export function CodeBlockTab(props: ComponentProps<typeof TabsContent>) {
  return <TabsContent {...props} />;
}
